[workspace]
members = [
  "practice-tool", 
  "lib/hudhook",
  "lib/imgui-dx11",
  "lib/libds3",
  "lib/macro-param",
  "xtask",
]

[profile.dev]
opt-level = 2

[profile.release]
lto = true
codegen-units = 1
opt-level = 3
