#
# Example configuration file.
# Pick key values from https://docs.microsoft.com/en-us/windows/win32/inputdev/virtual-key-codes
#
[mappings]

interact = "I"     # Toggle current command
next = "J"         # Go to next command
prev = "K"         # Go to prev command
display = "VK_F11"  # Show/hide tool window

# List of available commands to map:

all_no_damage = "VK_F5"
no_death = "VK_F6"
one_shot = "VK_F9"
inf_stamina = "VK_F2"
inf_focus = "VK_F3"
inf_consumables = "VK_F4"
save_position = "VK_F7"
load_position = "VK_F1"
souls = "O"
quitout = "P"
deathcam = "VK_F8"
evt_draw = "5"
evt_disable = "6"
ai_disable = "7"
rend_chr = "8"
rend_map = "9"
rend_obj = "0"
gravity = "VK_F10"

[settings]
# log_level - Possible values from most to least verbose:
# trace, debug, info, warn, error
# trace and debug will also log to a console window.
log_level = "info"
