commands = [
  { cmd = "savefile_manager", hotkey = "oem_3" },
  { cmd = "flag", flag = "all_no_damage", hotkey = "1" },
  { cmd = "flag", flag = "inf_stamina", hotkey = "2" },
  { cmd = "flag", flag = "inf_focus", hotkey = "3" },
  { cmd = "flag", flag = "inf_consumables", hotkey = "4" },
  { cmd = "flag", flag = "deathcam", hotkey = "5" },
  { cmd = "flag", flag = "no_death", hotkey = "6" },
  { cmd = "flag", flag = "one_shot", hotkey = "7" },
  { cmd = "flag", flag = "evt_draw", hotkey = "F1" },
  { cmd = "flag", flag = "evt_disable", hotkey = "F2" },
  { cmd = "flag", flag = "ai_disable", hotkey = "F3" },
  { cmd = "flag", flag = "rend_chr", hotkey = "F4" },
  { cmd = "flag", flag = "rend_obj", hotkey = "F5" },
  { cmd = "flag", flag = "rend_map", hotkey = "F6" },
  { cmd = "flag", flag = "rend_mesh_hi", hotkey = "F7" },
  { cmd = "flag", flag = "rend_mesh_lo", hotkey = "F8" },
  { cmd = "flag", flag = "all_draw_hit", hotkey = "F9" },
  { cmd = "flag", flag = "ik_foot_ray", hotkey = "F9" },
  { cmd = "flag", flag = "debug_sphere_1", hotkey = "F9" },
  { cmd = "flag", flag = "debug_sphere_2", hotkey = "F9" },
  { cmd = "flag", flag = "gravity", hotkey = "F10" },
  { cmd = "position", hotkey = "H" },
  { cmd = "position", hotkey = "J" },
  { cmd = "position", hotkey = "K" },
  { cmd = "speed", cycle_values = [1, 3], hotkey = "8" },
  { cmd = "souls", amount = 10000, hotkey = "9" },
  { cmd = "quitout", hotkey = "P" }
]

[settings]
log_level = "DEBUG"
display = "0"
down = "down"
up = "up"
left = "left"
right = "right"

