[settings]
log_level = "INFO"
interact = "VK_SPACE"
capture = "VK_F1"
display = "0"
next = "VK_DOWN"
prev = "VK_UP"

[[command]]
cmd = "quitout"
hotkey = "P"

[[command]]
cmd = "toggle"
flag = "all_no_damage"
hotkey = "VK_TAB"

[[command]]
cmd = "toggle"
flag = "no_death"
hotkey = "VK_F1"

[[command]]
cmd = "position"
hotkey_save = "N"
hotkey_load = "M"
