[package]
name = "jdsd_dsiii_practice_tool"
version = "1.2.0"
authors = ["Andrea Venuta <venutawebdesign@gmail.com>"]
edition = "2021"

[features]
focus = []
item_spawn = []

[[bin]]
name = "jdsd_dsiii_practice_tool"
path = "src/main.rs"

[lib]
crate-type = ["cdylib", "rlib"]
name = "libjdsd_dsiii_practice_tool"

[dependencies]
hudhook = { path = "../hudhook" }
log = "0.4.14"
simplelog = "0.8.0"
log-panics = "2.0.0"
lazy_static = "1.4.0"
toml = "0.5.6"
serde = { version = "1.0.115", features = ["derive"] }
serde_json = "1.0.57"
pkg-version = "1.0.0"
ureq = { version = "1.4.1", features = ["json"] }
winapi = { version = "0.3.9", features = ["winuser", "minwindef", "windef", "xinput"] }
open = "1.4.0"
semver = "0.11.0"
libloading = "0.6"
clap = "2.33.3"
glutin = "0.26.0"
glium = "0.29.0"
clipboard = "0.5"
dynasm = "1.0.0"
dynasmrt = "1.0.0"
regex = "1"
chrono = "0.4.19"
walkdir = "2.3.2"
imgui = "0.8.0"
anyhow = "1.0.48"
widestring = "0.5.1"
